version: "3.8"
services:
  nginx:
      image: nginx:latest
      container_name: nginx-proxy
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
      depends_on:
        - app1

  postgres-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: PEP1_Tingeso
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  app1:
    container_name: proyecto_1
    image: fernandoper501/proyecto_1
    ports:
      - "8091:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/PEP1_Tingeso
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-db